import { MigrationInterface, QueryRunner } from "typeorm";

export class PostgresBaseline1777382581956 implements MigrationInterface {
    name = 'PostgresBaseline1777382581956'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "votes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "pollId" integer, "optionId" integer, "userId" integer, CONSTRAINT "UQ_votes_poll_user" UNIQUE ("pollId", "userId"), CONSTRAINT "PK_f3d9fd4a0af865152c3f59db8ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_votes_option" ON "votes" ("optionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_votes_poll" ON "votes" ("pollId") `);
        await queryRunner.query(`CREATE TYPE "public"."poll_option_type_enum" AS ENUM('text', 'user')`);
        await queryRunner.query(`CREATE TABLE "poll_options" ("id" SERIAL NOT NULL, "label" character varying, "type" "public"."poll_option_type_enum" NOT NULL, "pollId" integer, "userId" integer, CONSTRAINT "PK_f52aac4865d291e3658dedf9083" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."poll_type_enum" AS ENUM('tournament', 'global', 'message')`);
        await queryRunner.query(`CREATE TABLE "polls" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL DEFAULT '', "type" "public"."poll_type_enum" NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "tournamentId" integer, "chatId" integer, "messageId" integer, CONSTRAINT "PK_b9bbb8fc7b142553c518ddffbb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tournaments" ("id" SERIAL NOT NULL, "game_type" character varying NOT NULL, "game_ref_id" integer NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "entry_fee" numeric NOT NULL, "prize_pool" numeric NOT NULL, "max_players" integer NOT NULL, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "is_super" boolean NOT NULL DEFAULT false, "Xp_condition" integer NOT NULL DEFAULT '0', "champion_achievement_id" integer, "audience_achievement_id" integer, "audience_poll_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "createdById" integer, CONSTRAINT "PK_6d5d129da7a80cf99e8ad4833a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_type_enum" AS ENUM('direct', 'channel')`);
        await queryRunner.query(`CREATE TABLE "chats" ("id" SERIAL NOT NULL, "type" "public"."chat_type_enum" NOT NULL, "title" character varying, "allow_user_messages" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "createdById" integer, "tournament_id" integer, CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_type_enum" AS ENUM('text', 'cta', 'poll', 'navigation')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" SERIAL NOT NULL, "content" text NOT NULL, "type" "public"."message_type_enum" NOT NULL DEFAULT 'text', "data" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "chatId" integer, "senderId" integer, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pubg_registrations" ("id" SERIAL NOT NULL, "paid" boolean NOT NULL DEFAULT false, "payment_method" character varying, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "tournamentId" integer, "userId" integer, CONSTRAINT "PK_a9033a45a4b47d04096a53367b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reel_comments" ("id" SERIAL NOT NULL, "comment" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "reelId" integer, "userId" integer, CONSTRAINT "PK_b38c18cfafa042b7714e32ef837" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reel_likes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "reelId" integer, "userId" integer, CONSTRAINT "PK_5496eac4580cf69396c81ab7b6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reels" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "video_url" character varying NOT NULL, "video_public_id" character varying, "description" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_e5ecdc818bad986f1eb0a5d7a2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."friend_status_enum" AS ENUM('pending', 'accepted', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "friends" ("user_id" integer NOT NULL, "friend_user_id" integer NOT NULL, "status" "public"."friend_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f46da3e4cf7f25532a157587c35" PRIMARY KEY ("user_id", "friend_user_id"))`);
        await queryRunner.query(`CREATE TABLE "user_notifications" ("id" SERIAL NOT NULL, "type" character varying(64) NOT NULL, "title" character varying(512) NOT NULL, "body" text NOT NULL, "data" jsonb, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer, CONSTRAINT "PK_569622b0fd6e6ab3661de985a2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" SERIAL NOT NULL, "balance" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, CONSTRAINT "REL_2ecdb33f23e9a6fc392025c0b9" UNIQUE ("userId"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "packages" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "price" numeric(10,2) NOT NULL, "coins" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_020801f620e21f943ead9311c98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" SERIAL NOT NULL, "price" numeric(10,2) NOT NULL, "coins" integer NOT NULL, "status" "public"."payment_status_enum" NOT NULL DEFAULT 'pending', "method" character varying, "reference" character varying, "approved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "packageId" integer NOT NULL, "approvedById" integer, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_tx_type_enum" AS ENUM('deposit', 'spend', 'refund')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_tx_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" SERIAL NOT NULL, "amount" integer NOT NULL, "type" "public"."wallet_tx_type_enum" NOT NULL, "status" "public"."wallet_tx_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "paymentId" integer, "tournamentId" integer, CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('user', 'admin', 'super_admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "full_name" character varying NOT NULL, "gamer_name" character varying NOT NULL, "profile_picture_url" character varying, "avatar_public_id" character varying, "email" character varying NOT NULL, "phone" character varying NOT NULL, "country" character varying, "password_hash" character varying NOT NULL, "role" "public"."user_role_enum" NOT NULL DEFAULT 'user', "is_active" boolean NOT NULL DEFAULT true, "coins" numeric NOT NULL DEFAULT '0', "xp_points" integer NOT NULL DEFAULT '0', "expo_push_token" text, "expo_push_token_updated_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "selected_achievement_id" integer, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_achievements" ("id" SERIAL NOT NULL, "obtained_at" TIMESTAMP WITH TIME ZONE NOT NULL, "displayed" boolean NOT NULL DEFAULT false, "userId" integer, "achievementId" integer, CONSTRAINT "PK_3d94aba7e9ed55365f68b5e77fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."achievement_type_enum" AS ENUM('tournament_join', 'tournament_win', 'tournament_rank', 'poll_participation', 'poll_win', 'highlight', 'custom', 'event_special')`);
        await queryRunner.query(`CREATE TYPE "public"."achievement_logic_type_enum" AS ENUM('progress', 'event', 'manual')`);
        await queryRunner.query(`CREATE TABLE "achievements" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "color_theme" character varying, "icon_url" character varying NOT NULL, "icon_public_id" character varying, "xp_reward" integer NOT NULL DEFAULT '0', "repeatable" boolean NOT NULL DEFAULT false, "type" "public"."achievement_type_enum" NOT NULL DEFAULT 'custom', "logic_type" "public"."achievement_logic_type_enum" NOT NULL DEFAULT 'manual', "target" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bc19c37c6249f70186f318d71d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_members" ("chat_id" integer NOT NULL, "user_id" integer NOT NULL, "role" character varying NOT NULL DEFAULT 'member', CONSTRAINT "PK_b4a04a57c87d984b806c95eac6d" PRIMARY KEY ("chat_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "highlights" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer, "tournament_id" integer, "reel_id" integer, CONSTRAINT "PK_d1c0c3c4b7c722041ea0c626411" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hero_content" ("id" SERIAL NOT NULL, "image" character varying NOT NULL, "image_public_id" character varying, "title" character varying NOT NULL, "description" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc1b31914af0485de046d765a02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pubg_type_enum" AS ENUM('solo', 'duo', 'squad')`);
        await queryRunner.query(`CREATE TABLE "pubg_game" ("id" SERIAL NOT NULL, "type" "public"."pubg_type_enum" NOT NULL, "image" character varying NOT NULL, "image_public_id" character varying, "map" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_50030a17345ef372f03723490d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pubg_registration_field_type_enum" AS ENUM('string', 'number', 'boolean', 'select')`);
        await queryRunner.query(`CREATE TABLE "pubg_registration_fields" ("id" SERIAL NOT NULL, "label" character varying NOT NULL, "type" "public"."pubg_registration_field_type_enum" NOT NULL, "options" text, "required" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "tournamentId" integer, CONSTRAINT "PK_6ee8dad5c72e2d38bbcd40d6481" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pubg_registration_field_values" ("id" SERIAL NOT NULL, "value" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "registrationId" integer, "fieldId" integer, CONSTRAINT "PK_feea13182ab5d27e72703ba07fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer, "creator_id" integer, "reel_id" integer, "comment_id" integer, CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_tags_user_comment" ON "tags" ("user_id", "comment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tags_comment" ON "tags" ("comment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tags_reel" ON "tags" ("reel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tags_creator" ON "tags" ("creator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_tags_user" ON "tags" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "tournament_winners" ("tournament_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_2de1387608834af3170dc8cfe99" PRIMARY KEY ("tournament_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39de76fe7a3738e77e0859eb54" ON "tournament_winners" ("tournament_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd6a7a1c94ca4da211c5df662e" ON "tournament_winners" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "pubg_registration_friends" ("registration_id" integer NOT NULL, "friend_id" integer NOT NULL, CONSTRAINT "PK_e29688ca0ca83028338e32c386a" PRIMARY KEY ("registration_id", "friend_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_67386a8b084f5f0b640b7e9738" ON "pubg_registration_friends" ("registration_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_69ce7d01981f95612fc088cc34" ON "pubg_registration_friends" ("friend_id") `);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_2e40638d2d3b898da1af363837c" FOREIGN KEY ("pollId") REFERENCES "polls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_70b83e1b0a90b9491cfdc73f52d" FOREIGN KEY ("optionId") REFERENCES "poll_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_5169384e31d0989699a318f3ca4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_options" ADD CONSTRAINT "FK_4edaafa5d0ea2a447af004706a4" FOREIGN KEY ("pollId") REFERENCES "polls"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poll_options" ADD CONSTRAINT "FK_fcfd1b745b466635fe1a4e41eeb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "polls" ADD CONSTRAINT "FK_6c1a7ed2a4f927a77a631c6b71e" FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "polls" ADD CONSTRAINT "FK_13d927f12734815f5ae75391a84" FOREIGN KEY ("chatId") REFERENCES "chats"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "polls" ADD CONSTRAINT "FK_a98d3cf1094db401a5d1ef290cd" FOREIGN KEY ("messageId") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_5ff236c228350de491d16d3a78d" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_fa7cbf53930e01a370b3841a1bc" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_4282ee05757f66b9a92d26c3256" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_36bc604c820bb9adc4c75cd4115" FOREIGN KEY ("chatId") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pubg_registrations" ADD CONSTRAINT "FK_2caf2bf5bfac04e7a2a18ead5bd" FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pubg_registrations" ADD CONSTRAINT "FK_cad3b829ce0016d7ad12cae3a0e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reel_comments" ADD CONSTRAINT "FK_246099081e9f2ad3e120a131f9f" FOREIGN KEY ("reelId") REFERENCES "reels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reel_comments" ADD CONSTRAINT "FK_0caf86b86e8ff78b362a866cf58" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "FK_786307fb6852744f867a7da8fbf" FOREIGN KEY ("reelId") REFERENCES "reels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "FK_52f522090c41ae6c4d90edff020" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reels" ADD CONSTRAINT "FK_a6c4a1abb80e3e35063cf2421f1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friends" ADD CONSTRAINT "FK_f2534e418d51fa6e5e8cdd4b480" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friends" ADD CONSTRAINT "FK_83cfa95763744f6447a6da9ae40" FOREIGN KEY ("friend_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notifications" ADD CONSTRAINT "FK_ae9b1d1f1fe780ef8e3e7d0c0f6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_f14a98c8d21e57b7ddf02940bad" FOREIGN KEY ("packageId") REFERENCES "packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e44c192c960ba9c2ca0ca705d97" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_69454773f1e666a14c6a9539353" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_154435de0ddfa1edafd4f701293" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_d6f5b5a918fb6e5c50d2640896c" FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_tournaments_champion_achievement" FOREIGN KEY ("champion_achievement_id") REFERENCES "achievements"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_tournaments_audience_achievement" FOREIGN KEY ("audience_achievement_id") REFERENCES "achievements"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_tournaments_audience_poll" FOREIGN KEY ("audience_poll_id") REFERENCES "polls"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4f67cdb337a6db0c1f1f631fba3" FOREIGN KEY ("selected_achievement_id") REFERENCES "achievements"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_3ac6bc9da3e8a56f3f7082012dd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74" FOREIGN KEY ("achievementId") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_members" ADD CONSTRAINT "FK_29ffb4b6edf59a7862129765339" FOREIGN KEY ("chat_id") REFERENCES "chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_members" ADD CONSTRAINT "FK_9dc61e92eed1dc151c2b2ef01a0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "highlights" ADD CONSTRAINT "FK_ef5faa0b9245db024880d12bfae" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "highlights" ADD CONSTRAINT "FK_1d856b1c09ebb1ffe5e4a3f887d" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "highlights" ADD CONSTRAINT "FK_05709d1b6dfd2ce735ba7e79c6e" FOREIGN KEY ("reel_id") REFERENCES "reels"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_fields" ADD CONSTRAINT "FK_6cad066ed90e190e279674a33fa" FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_field_values" ADD CONSTRAINT "FK_05bc85dbe1434713d37678d4db0" FOREIGN KEY ("registrationId") REFERENCES "pubg_registrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_field_values" ADD CONSTRAINT "FK_813fbb5e9e28dc225c9a2d70eb6" FOREIGN KEY ("fieldId") REFERENCES "pubg_registration_fields"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_74603743868d1e4f4fc2c0225b6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_78e65343656c6c8895a87e1efb5" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_41b544c249ff02e601366c8ca1a" FOREIGN KEY ("reel_id") REFERENCES "reels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_8a6937203e0ba1d52dcedf575f1" FOREIGN KEY ("comment_id") REFERENCES "reel_comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_winners" ADD CONSTRAINT "FK_39de76fe7a3738e77e0859eb548" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tournament_winners" ADD CONSTRAINT "FK_dd6a7a1c94ca4da211c5df662ec" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_friends" ADD CONSTRAINT "FK_pubg_registration_friends_registration" FOREIGN KEY ("registration_id") REFERENCES "pubg_registrations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_friends" ADD CONSTRAINT "FK_pubg_registration_friends_friend" FOREIGN KEY ("friend_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pubg_registration_friends" DROP CONSTRAINT "FK_pubg_registration_friends_friend"`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_friends" DROP CONSTRAINT "FK_pubg_registration_friends_registration"`);
        await queryRunner.query(`ALTER TABLE "tournament_winners" DROP CONSTRAINT "FK_dd6a7a1c94ca4da211c5df662ec"`);
        await queryRunner.query(`ALTER TABLE "tournament_winners" DROP CONSTRAINT "FK_39de76fe7a3738e77e0859eb548"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_8a6937203e0ba1d52dcedf575f1"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_41b544c249ff02e601366c8ca1a"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_78e65343656c6c8895a87e1efb5"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_74603743868d1e4f4fc2c0225b6"`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_field_values" DROP CONSTRAINT "FK_813fbb5e9e28dc225c9a2d70eb6"`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_field_values" DROP CONSTRAINT "FK_05bc85dbe1434713d37678d4db0"`);
        await queryRunner.query(`ALTER TABLE "pubg_registration_fields" DROP CONSTRAINT "FK_6cad066ed90e190e279674a33fa"`);
        await queryRunner.query(`ALTER TABLE "highlights" DROP CONSTRAINT "FK_05709d1b6dfd2ce735ba7e79c6e"`);
        await queryRunner.query(`ALTER TABLE "highlights" DROP CONSTRAINT "FK_1d856b1c09ebb1ffe5e4a3f887d"`);
        await queryRunner.query(`ALTER TABLE "highlights" DROP CONSTRAINT "FK_ef5faa0b9245db024880d12bfae"`);
        await queryRunner.query(`ALTER TABLE "chat_members" DROP CONSTRAINT "FK_9dc61e92eed1dc151c2b2ef01a0"`);
        await queryRunner.query(`ALTER TABLE "chat_members" DROP CONSTRAINT "FK_29ffb4b6edf59a7862129765339"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_3ac6bc9da3e8a56f3f7082012dd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4f67cdb337a6db0c1f1f631fba3"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_d6f5b5a918fb6e5c50d2640896c"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_154435de0ddfa1edafd4f701293"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_69454773f1e666a14c6a9539353"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e44c192c960ba9c2ca0ca705d97"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_f14a98c8d21e57b7ddf02940bad"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "user_notifications" DROP CONSTRAINT "FK_ae9b1d1f1fe780ef8e3e7d0c0f6"`);
        await queryRunner.query(`ALTER TABLE "friends" DROP CONSTRAINT "FK_83cfa95763744f6447a6da9ae40"`);
        await queryRunner.query(`ALTER TABLE "friends" DROP CONSTRAINT "FK_f2534e418d51fa6e5e8cdd4b480"`);
        await queryRunner.query(`ALTER TABLE "reels" DROP CONSTRAINT "FK_a6c4a1abb80e3e35063cf2421f1"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "FK_52f522090c41ae6c4d90edff020"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "FK_786307fb6852744f867a7da8fbf"`);
        await queryRunner.query(`ALTER TABLE "reel_comments" DROP CONSTRAINT "FK_0caf86b86e8ff78b362a866cf58"`);
        await queryRunner.query(`ALTER TABLE "reel_comments" DROP CONSTRAINT "FK_246099081e9f2ad3e120a131f9f"`);
        await queryRunner.query(`ALTER TABLE "pubg_registrations" DROP CONSTRAINT "FK_cad3b829ce0016d7ad12cae3a0e"`);
        await queryRunner.query(`ALTER TABLE "pubg_registrations" DROP CONSTRAINT "FK_2caf2bf5bfac04e7a2a18ead5bd"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_36bc604c820bb9adc4c75cd4115"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_4282ee05757f66b9a92d26c3256"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_fa7cbf53930e01a370b3841a1bc"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_tournaments_audience_poll"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_tournaments_audience_achievement"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_tournaments_champion_achievement"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_5ff236c228350de491d16d3a78d"`);
        await queryRunner.query(`ALTER TABLE "polls" DROP CONSTRAINT "FK_a98d3cf1094db401a5d1ef290cd"`);
        await queryRunner.query(`ALTER TABLE "polls" DROP CONSTRAINT "FK_13d927f12734815f5ae75391a84"`);
        await queryRunner.query(`ALTER TABLE "polls" DROP CONSTRAINT "FK_6c1a7ed2a4f927a77a631c6b71e"`);
        await queryRunner.query(`ALTER TABLE "poll_options" DROP CONSTRAINT "FK_fcfd1b745b466635fe1a4e41eeb"`);
        await queryRunner.query(`ALTER TABLE "poll_options" DROP CONSTRAINT "FK_4edaafa5d0ea2a447af004706a4"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_5169384e31d0989699a318f3ca4"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_70b83e1b0a90b9491cfdc73f52d"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_2e40638d2d3b898da1af363837c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69ce7d01981f95612fc088cc34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67386a8b084f5f0b640b7e9738"`);
        await queryRunner.query(`DROP TABLE "pubg_registration_friends"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd6a7a1c94ca4da211c5df662e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39de76fe7a3738e77e0859eb54"`);
        await queryRunner.query(`DROP TABLE "tournament_winners"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tags_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tags_creator"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tags_reel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tags_comment"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_tags_user_comment"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "pubg_registration_field_values"`);
        await queryRunner.query(`DROP TABLE "pubg_registration_fields"`);
        await queryRunner.query(`DROP TYPE "public"."pubg_registration_field_type_enum"`);
        await queryRunner.query(`DROP TABLE "pubg_game"`);
        await queryRunner.query(`DROP TYPE "public"."pubg_type_enum"`);
        await queryRunner.query(`DROP TABLE "hero_content"`);
        await queryRunner.query(`DROP TABLE "highlights"`);
        await queryRunner.query(`DROP TABLE "chat_members"`);
        await queryRunner.query(`DROP TABLE "achievements"`);
        await queryRunner.query(`DROP TYPE "public"."achievement_logic_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."achievement_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_achievements"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_tx_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_tx_type_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "packages"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TABLE "user_notifications"`);
        await queryRunner.query(`DROP TABLE "friends"`);
        await queryRunner.query(`DROP TYPE "public"."friend_status_enum"`);
        await queryRunner.query(`DROP TABLE "reels"`);
        await queryRunner.query(`DROP TABLE "reel_likes"`);
        await queryRunner.query(`DROP TABLE "reel_comments"`);
        await queryRunner.query(`DROP TABLE "pubg_registrations"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."message_type_enum"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TYPE "public"."chat_type_enum"`);
        await queryRunner.query(`DROP TABLE "tournaments"`);
        await queryRunner.query(`DROP TABLE "polls"`);
        await queryRunner.query(`DROP TYPE "public"."poll_type_enum"`);
        await queryRunner.query(`DROP TABLE "poll_options"`);
        await queryRunner.query(`DROP TYPE "public"."poll_option_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_votes_poll"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_votes_option"`);
        await queryRunner.query(`DROP TABLE "votes"`);
    }

}
